### ISSUE TITLE
ad-hoc multi-hop problem

### ISSUE THREAD

**Issue by u284976** [DSG-UniFE/ramp#1]
i was trying build a simple ad-hoc network by [mininet-wifi](https://github.com/intrig-unicamp/mininet-wifi)

that Emulator give a example [ad-hoc environment](https://github.com/intrig-unicamp/mininet-wifi/blob/master/examples/adhoc.py) like below:
sta1 <---> sta2 <---> sta3

these three all use ad-hoc to communication
and i run the SDN controller on sta1,
SDN client on sta1, sta2 sta3

Neighbors can communicate correct
sta1 <---> sta2
sta2 <---> sta3

but sta1 can't "find node" sta3
i thought SDN client will spread neighbor message to around neighbor may like:
sta1 "find node"
sta2 receive message by sta1, check TTL>0, send to sta3
sta3 response message

Did i understand wrong? How can i fix it :'c

**Comment by u284976** [comment]
I re-read the [paper](https://ieeexplore.ieee.org/document/5546785/citations?tabFilter=papers#citations) found some keywords about this case

> Dispatch manages broadcast packets as follows:
> b) if TTL>0, it gathers the set of neighbors from Heartbeater and then sends the packet to any neighbor, except for nodes in the same subnet of the sender.

so i need to set the previously sta2 ip cross the subnet
one NIC is sta2-wlan0 ip=10.0.0.2/24
another NIC is sta2-wlan1 ip = 10.0.1.2/24
and modify sta3 ip address to 10.0.1.3/24

it will be work!

**Comment by davidMonnuar** [comment]
Hi @u284976,

thank you for your interest, you're right about the second post. Ramp works with the assumption that multi hop paths are composed of subnets with different address spaces. 

So sta1 and sta2 should be connected with a subnet different from the one that connects sta2 and sta3. To do that sta2 must use 2 different NICs.

Feel free to ask for any kind of doubt and also in case you'd like to collaborate with us in the development of Ramp or for any reasearch activity.

Best regards,

Dmitrij

**Comment by u284976** [comment]
Hi @davidMonnuar ,
Thank you for your kind description.

Regards,
Y.T. Chen

**Comment by u284976** [comment]
Hi @davidMonnuar ,
I have some new problems want to ask, and I added a new Issue
Looking forward to your reply.

Best Regards,
Y.T. Chen
